### ISSUE TITLE
not working on multi-site

### ISSUE THREAD

**Issue by davidtowoju** [turtlepod/fx-updater#10]
Thank you for releasing this plugin. It's really useful.
However, I noticed it doesn't work for me on multi-site. Have you experienced this before?

**Comment by turtlepod** [comment]
You need to network activate or activate it in main site.
The one handling the update is the main site. if the plugin is not active. the code is not even loaded.

So, Group updater is  probably better for multisite, because the updater can be added in separate plugin which can be network-activated:
https://genbumedia.com/docs/fx-updater-groups/

**Comment by davidtowoju** [comment]
Thanks, it works now after a network activation

**Comment by turtlepod** [comment]
That's awesome!
Thank you for confirming.
