### ISSUE TITLE
Any thoughts on how to make this work on Multisite?

### ISSUE THREAD

**Issue by oobi** [turtlepod/fx-updater#8]
This is a really neat little plugin - we've been using it to serve some of our small  plugins to various sites (stuff that really isn't suitable or general enough for public consumption but warrants keeping updated periodically).

We've hit a snag with multisite installations though, where wordpress can't detect that the update is available unless the plugin is network activated. What I'd love to be able to do is have the plugin active on a per-site basis but still be able to detect and install updates.

Is that possible or have I missed some configuration?

Currently the workaround seems to be
- network activate
- force a plugin check (using WP Crontrol) 
- update
- network deactivate

Any thoughts or pointers?

**Comment by turtlepod** [comment]
It won't work, because the plugin is not even loaded (if not network activated/activated in main site of multisite)

Solution:
Create a group updater plugin and activate it network wide:
https://genbumedia.com/docs/fx-updater-groups/

Basically you can create something like:

WooCommerce Updater:
https://docs.woocommerce.com/document/woocommerce-helper/

Elegant Themes Updater:
https://www.elegantthemes.com/gallery/divi/documentation/update-legacy/

**Comment by oobi** [comment]
Thanks for that! I had not fully grasped the purpose of "groups" but that makes complete sense.
